"""Centralized default values for TransVBA.

This module provides a single source of truth for all default format settings.
Values here match the VBA original's fallback defaults.
"""

# Font choices
DEFAULT_BODY_FONT = "宋体"
DEFAULT_TITLE_FONT = "宋体"
DEFAULT_TABLE_TITLE_FONT = "黑体"
DEFAULT_TABLE_BODY_FONT = "宋体"
DEFAULT_FIGURE_TITLE_FONT = "黑体"
DEFAULT_TOC_FONT = "宋体"
DEFAULT_ASCII_FONT = "Times New Roman"

# Size choices (Chinese typography labels)
DEFAULT_BODY_SIZE = "小四"
DEFAULT_TITLE_SIZE = "小四"
DEFAULT_TABLE_TITLE_SIZE = "小四"
DEFAULT_TABLE_BODY_SIZE = "五号"
DEFAULT_FIGURE_TITLE_SIZE = "小四"
DEFAULT_TOC_SIZE = "小四"

# Spacing
DEFAULT_BODY_SPACING = 1.5
DEFAULT_TITLE_LINE_SPACING = 1.5
DEFAULT_TABLE_TITLE_SPACING = 1.5
DEFAULT_TABLE_SPACING = 1.0
DEFAULT_FIGURE_TITLE_SPACING = 1.5
DEFAULT_TOC_SPACING = 1.5

# Paragraph spacing (lines)
DEFAULT_BODY_BEFORE_LINES = 0.0
DEFAULT_BODY_AFTER_LINES = 0.0
DEFAULT_TITLE_BEFORE_LINES = 0.5
DEFAULT_TITLE_AFTER_LINES = 0.5

# Indentation
DEFAULT_BODY_LEFT_INDENT_CM = 0.0
DEFAULT_BODY_RIGHT_INDENT_CM = 0.0
DEFAULT_BODY_SPECIAL_INDENT = "首行缩进"
DEFAULT_BODY_SPECIAL_INDENT_CHARS = 2.0

# Alignment
DEFAULT_BODY_ALIGNMENT = "两端对齐"
DEFAULT_TITLE_ALIGNMENT = "左对齐"

# Boolean flags
DEFAULT_TITLE_BOLD = False
DEFAULT_TABLE_TITLE_BOLD = True
DEFAULT_FIGURE_TITLE_BOLD = True
DEFAULT_TOC_TITLE_BOLD = True
DEFAULT_TOC_ENTRY_BOLD = True
DEFAULT_TABLE_AUTO_FIT = True
DEFAULT_AUTO_DETECT_NUMERIC_TITLES = True
DEFAULT_AUTO_DETECT_INCLUDE_LIST = True
DEFAULT_REMEMBER_SETTINGS = True
DEFAULT_PREFER_COM_RESOLVER = False

# Table formatting
DEFAULT_TABLE_LINE_WIDTH_PT = 0.5
DEFAULT_TABLE_ROW_HEIGHT_CM = 0.7

# TOC fixed defaults (not exposed in UI)
DEFAULT_TOC_LEVEL1_INDENT_CHARS = 0
DEFAULT_TOC_LEVEL2_INDENT_CHARS = 2
DEFAULT_TOC_LEVEL3_INDENT_CHARS = 4

# Cover page (封面) — Mode B defaults
DEFAULT_COVER_FONT = "宋体"
DEFAULT_COVER_SIZE = "二号"
DEFAULT_COVER_BOLD = True
DEFAULT_COVER_LINE_SPACING = 1.5
DEFAULT_COVER_ALIGNMENT = "居中"
DEFAULT_COVER_MAX_LENGTH = 80
DEFAULT_COVER_SEARCH_PARAGRAPHS = 15

# Appendix (附件) — Mode B defaults
DEFAULT_APPENDIX_TITLE_FONT = "宋体"
DEFAULT_APPENDIX_TITLE_SIZE = "小四"
DEFAULT_APPENDIX_TITLE_BOLD = True
DEFAULT_APPENDIX_TITLE_LINE_SPACING = 1.5
DEFAULT_APPENDIX_BODY_FONT = "宋体"
DEFAULT_APPENDIX_BODY_SIZE = "小五"
DEFAULT_APPENDIX_BODY_BOLD = False
DEFAULT_APPENDIX_BODY_LINE_SPACING = 1.0

# Header (页眉) — Mode B defaults
DEFAULT_HEADER_FONT = "宋体"
DEFAULT_HEADER_SIZE = "小五"
DEFAULT_HEADER_BOLD = False
DEFAULT_HEADER_LINE_SPACING = 1.0
